cartapp/urls.py
from django.urls import path
# from views import SearchResult
from . import views

app_name='cartapp'

urlpatterns=[
    path('add/<int:product_id>/',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
path('cart_delete/<int:product_id>/',views.cart_delete,name='cart_delete'),
]

searchapp/urls.py
from django.urls import path
# from views import SearchResult
from . import views

app_name='searchapp'
urlpatterns=[
    path('',views.SearchResult,name='SearchResult'),
]

shoppingapp/urls.py
from . import views
from django.urls import path
app_name='shoppingapp'
urlpatterns = [
    # path('',views.base,name='base'),
    path('',views.allproductcat,name='allproductcat'),
    path('<slug:c_slug>/',views.allproductcat,name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/',views.productDetails,name='PoductCat_urls')
]

shoppingproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/',include("shoppingapp.urls")),
    path('search/',include('searchapp.urls')),
    path('cart/',include('cartapp.urls')),

]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cartapp/models.py
from django.db import models
from shoppingapp.models import Product
# Create your models here.
class Cart(models.Model):
    cart_id=models.CharField(max_length=250,blank=True)
    date_added=models.DateField(auto_now_add=True)

    class Meta:
        db_table='Cart'
        ordering=['date_added']
    def __str__(self):
        return '{}'.format(self.cart_id)
class CartItem(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    active=models.BooleanField(default=True)
    class Meta:
        db_table='CartItem'
    def sub_total(self):
        return self.product.price * self.quantity
    def __str__(self):
        return '{}'.format(self,Product)

searchapp/models.py
from django.db import models
from django.urls import reverse
class Product(models.Model):

    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    productdiscr=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    # category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)
    def get_url(self):
     return reverse('shoppingapp:PoductCat_urls', args=[self.category.slug,self.slug])

from django.db import models

# Create your models here.

shoppingapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)

    class Meta:
        ordering=('name',)
        verbose_name='category'
        verbose_name_plural='categories'
    def get_url(self):
        return reverse('shoppingapp:products_by_category',args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)
class Product(models.Model):

    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    productdiscr=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now_add=True)
    def get_url(self):
     return reverse('shoppingapp:PoductCat_urls', args=[self.category.slug,self.slug])


    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def __str__(self):
        return '{}'.format(self.name)

cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
#importing librery
from shoppingapp.models import Product
from .models import Cart,CartItem
from django.core.exceptions import ObjectDoesNotExist
# Create your views here.

#creating cart id (session)
def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart
#add to cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock: #it helps not increase more than stock
            cart_item.quantity += 1  # Increment the quantity
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
            product=product,
            quantity=1,
            cart=cart
        )
        cart_item.save()

    return redirect('cartapp:cart_detail')
def cart_detail(request,total=0,counter=0,cart_items=None):
    try:
        cart=Cart.objects.get(cart_id=_cart_id(request))
        cart_items=CartItem.objects.filter(cart=cart,active=True)
        for cart_item in cart_items:
            total+=(cart_item.product.price * cart_item.quantity)
            counter +=cart_item.quantity

    except ObjectDoesNotExist:
        pass
    #{ or  dict we can use
    return render(request,'cart.html',dict(cart_items=cart_items,total=total,counter=counter))
#to remove product from cart
def cart_remove(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    if cart_item.quantity >= 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cartapp:cart_detail')
def cart_delete(request,product_id):
    cart=Cart.objects.get(cart_id=_cart_id(request))
    product=get_object_or_404(Product,id=product_id)
    cart_item=CartItem.objects.get(product=product,cart=cart)
    cart_item.delete()
    return redirect('cartapp:cart_detail')

searchapp/views.py
from django.shortcuts import render
from shoppingapp.models import Product
#for more things using Q
from django.db.models import Q
# Create your views here.
def SearchResult(request):
    products=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        products=Product.objects.all().filter(Q(name__contains=query) | Q(productdiscr__contains=query))
    return render(request,'search.html',{'query_key':query, 'products_key':products})

shoppingapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import RequestContext
from django.db.models import Q
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage, PageNotAnInteger


# def base(request):
#     print("here 1")
#     return render(request, 'base.html')

def allproductcat(request, c_slug=None):
    print("here 2")
    global paginator_page
    c_page = None
    products_all = None

    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_all = Product.objects.all().filter(category=c_page, available=True)
    else:
        products_all = Product.objects.all().filter(available=True)

     #this for page numbering 6 is the max products in productpage
    paginator=Paginator(products_all,6)
    try:
        page=int(request.GET.get('page','1'))
    except:
        page=1
    try:
        products=paginator.page(page)
    except (EmptyPage,InvalidPage):
        products=paginator.page(paginator.num_pages)
    # Move the return statement outside the else block
    return render(request, "category.html", {'category': c_page, 'products': products,})
def productDetails(request,c_slug,product_slug):
    print("here 3")
    try:
        product_value=Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'product.html', {'product_key': product_value})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link  href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
      <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script src="https://kit.fontawesome.com/ddca60fc28.js" crossorigin="anonymous"></script>
     <meta name="description" content="{% block metadescription %}{% endblock %}">
    <title>Title</title>
</head>
<body>
<!--class="d-flex flex-column min-vh-100"-->
  <div class="container">

      {% include 'header.html' %}
      {% include 'navbar.html'%}

      {% block content %}

      {% endblock %}

    {% include 'footer.html' %}
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </div>
    </body>
    </html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
  THis is Cart page.proceed to review your items and place the order
{% endblock %}
{% block title %}
  cart-ABC company PVT LTD
{% endblock %}

{% block content %}
{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart is empty
        </h1>
        <br>
        <p class="text-center">
            Please click <a href="{% url 'shoppingapp:allproductcat' %}">Here</a>to continue shopping
        </p>

    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your shopping cart
        </h1>
        <br>

    </div>
</div>
<div class="row mx-auto">
<div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
    <table class="table my_custom_table">
        <thead class="my_custom_thead">
        <tr>
            <th colspan="5">
                Your Items
            </th>
        </tr>
        </thead>
        <tbody>
        {% for cart_item in cart_items %}
        <tr>
            <td>
                <a href="cart_item.product.get_absolute_url"><img src="{{cart_item.product.image.url}}" alt="no image" style="width:100px;height:100px" class="float-left rounded coustom_image"></a>

            </td>
            <td class="text-lef">
                {{cart_item.product.name}}
                <br>
                SKU:{{cart_item.product.id}}
                <br>
                Price:$ {{cart_item.product.price}}
                <br>
                Qty:{{cart_item.quantity}} x $ {{cart_item.product.price}}
                <br>
                <br>
            Sub Total:$ {{cart_item.sub_total}}
<!--            <td><br>-->
<!--            Sub Total:$ {{cart_item.sub_total}}-->

<!--            </td>-->
             {% if cart_item.quantity < cart_item.product.stock %}
            <td>
                <a href="{% url 'cartapp:add_cart'  cart_item.product.id%}" class="custom_a"><i class="fa fa-plus custom_icon"></i></a>
                &nbsp;<a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"> </i></a><br>
<!--                &nbsp;<a href="" class="custom_a"><i class="fa fa-minus custom_icon"> </i></a>-->
                &nbsp;<a href="{% url 'cartapp:cart_delete' cart_item.product.id %}" class="custom_icon"><i class="fa fa-trash custom_icon"> </i></a>
            </td>
            {% else %}
            <td>

                &nbsp;<a href="" class="custom_a"><i class="fa fa-plus custom_icon"> </i></a>
                <a href="{% url 'cartapp:cart_remove' cart_item.product.id %}" class="custom_a"><i class="fa fa-minus custom_icon"> </i></a>
                &nbsp;<a href="" class="custom_icon"><i class="fa fa-trash custom_icon"> </i></a>
            </td>
            {% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <table class="table my_custom_table">
            <thead class="my_custom_thead">
            <tr>
                <th>
                    Checkout
                </th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your cart items before payment.
                </td>
            </tr>
            <td class="text-left">
                Your Total is:<strong>{{ total }}</strong>

            </td>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'shoppingapp:allproductcat' %}" class="btn btn-secondary btn-block shop_btn">Checkout</a>
            <a href="{% url 'shoppingapp:allproductcat' %}" class="btn btn-primary btn-block shop_btn">Make Payment</a>

        </div>
    </div>
</div>
{% endif %}
{% endblock %}

templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to Advanture store where you can buys adventure items...
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ category.name }} -Advanture Store
    {% else %}
    See our new collections-Advanture Store
    {% endif %}
{% endblock %}


{% block content %}
{% if category %}
    <div>
         <div class="row my_row_class">
             <div class="mx-auto">
        <p>
            <a href="{% url 'shoppingapp:allproductcat' %}"> This is banner </a>
        </p>
                 </div>
        </div>
    </div>
{% endif %}
<div class="mx-auto">
    {% if category %}
    <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
</div>
    <br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>
    <p class="text-justify">{{category.description}}</p>
</div>
{% else %}
<div>
<img class="my_image my_image_padding" src="{% static 'img/banner1.jpg' %}" alt="our Products">
</div><br>
<div>
    <h1 class="text_center my_title"> Our Product collections</h1>
    <p class="tex-justify">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
</div>
{% endif %}


<div class="container">
    <div class="row mx_auto">
<!--        added .object_list afterproducts for page-->
        {% for pdt in products.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width: 10rem;">
                <a href="{{ pdt.get_url }}"><img class="card-img-top my_image" src="{{ pdt.image.url }}" alt="{{ pdt.name }}" style="height: 200px; width: 200px;"></a>
                 <div class="card-body">
                        <h3>{{ pdt.name }}</h3>
                        <p>INR {{ pdt.price }}</p>
                 </div>
            </div>
        </div>
        {%endfor%}

<!--        editing for page number-->
    <div class="pagenumber">
       <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}

        <hr>

        <div class="text-center">
            {% for pg in products.paginator.page_range %}

            <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
            <div> Previous  Next page</div>
        </div>
        {% endif %}
        </div>
    <br>
    </div>
    </div>

</div><br>
<!-- <div><p>hi</p></div>-->
{% endblock %}

templates/footer.html
<div class="certification_footer" >
  <p class="text-center">copy@adventure pvt ltd.all rights Reserved</p>
</div>

templates/header.html
{% load static %}
<header>
  <center>
    <a href="{%url 'shoppingapp:allproductcat' %}"><img src="{% static 'img/logo.png'%}" alt="logimage" width="100px" height="100px"></a>
  </center>
</header>

templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'shoppingapp:allproductcat' %}">HOME</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shoppingapp:allproductcat' %}">products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown {% if 'shoppingapp' in request.path %} active {% endif %}">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            SHOP
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'shoppingapp:allproductcat' %}">All Products</a></li>
             {% for pdt in links %}
            <li><a class="dropdown-item" href="{{pdt.get_url}}">{{pdt.name}}</a></li>
             {% endfor %}

            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        {% if item_count > 0 %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'cartapp:cart_detail' %}" ><i class="fa-solid fa-cart-shopping"></i>{{item_count}} Cart</a>
        </li>

<!--        else-->
<!--          <li class="nav-item">-->
<!--          <a class="nav-link" href="" ><i class="fa-solid fa-cart-shopping"></i>cart</a>-->
            {% endif %}
        </li>
      </ul>
      <form class="d-flex" role="search" action="{% url  'searchapp:SearchResult' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>
    </div>
  </div>
</nav>

templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {{ product_key.description|truncatewords:155 }}
{% endblock %}
{% block title %}
    {% if category %}
        {{ product_key.name }} -Advanture Store
    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p> <a href="{% url 'shoppingapp:allproductcat' %}">HOME</a>  | <a href="{{product_key.category.get_url}}">Category</a> | {{product_key.name}}</p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img class="product_image" src="{{product_key.image.url}}" alt="{{product_key.name}}">
        </div>
    </div>

    <div class="col-12 col-sm-12 col-md-12 col-lg-6">
        <div>
        <h3 style="color:Black">{{product_key.name}}</h3>
        <h2 class="my_product_price">$ {{product_key.price}}</h2>
        <h3>Product Discription</h3>
        <p>{{product_key.productdiscr}}</p>
        {% if product_key.stock <= 0 %}
            <p style="color:red">Out Of Stock</p>
            <a class="btn btn-secondary"href="{% url 'cartapp:add_cart' product_key.id %}">ADD TO CART</a>
        {% else %}
        <a class="btn btn-secondary"  href="{% url 'cartapp:add_cart' product_key.id %}" >Add to Cart</a>
        {% endif %}
    </div>

</div>
</div>
</div><br>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   we have verity of products
{% endblock %}
{% block title %}
  search
{% endblock %}

{% block content %}
<div>
    <div>
      <p class="text-center my_search_text">You have searched for:<b>"{{query_key}}"</b></p>
    </div>


    <div class="row mx_auto">
    <!--        added .object_list afterproducts for page-->
            {% for pdt in products_key %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
                <div class="card text-center" style="min-width: 10rem;">
                    <a href="{{ pdt.get_url }}"><img class="card-img-top my_image" src="{{ pdt.image.url }}" alt="{{ pdt.name }}" style="height: 200px; width: 200px;"></a>
                     <div class="card-body">
                            <h2>{{ pdt.name }}</h2>
                            <p>INR {{ pdt.price }}</p>
                     </div>
                </div>
            </div>
            {% empty %}
              <div class="row mx-auto">
                <p class="text-center my_search_text">0 results found</p>
              </div>

            {%endfor%}

    </div>
</div>
 {% endblock %}